server:
  port: 8084
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
debug: true

spring:
  application:
    name: boms-front-service
  cloud:
    config:
        enabled: false
    consul:
      host: 10.20.11.111
      port: 8500
      enabled: true
      discovery:
        enabled: true
        register: true
        serviceName: ${spring.application.name}
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        prefer-ip-address: true
        tags: urlprefix-/${spring.application.name}
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${spring.cloud.client.hostname}:${server.port}}}
        acl-token: p2BE1AtpwPbrxZdC6k+eXA==
#      config:
#        enabled: true #默认是true
#        format: YAML    # 表示consul上面文件的格式 有四种 YAML PROPERTIES KEY-VALUE FILES
#        data-key: paasconfig #表示consul上面的KEY值(或者说文件的名字) 默认是data
        #watch:
        #  enabled: true #实时刷新配置
        #prefix: #设置配置值的基本文件夹
        #default-context: #设置所有应用程序使用的文件夹名称
        #profile-separator: #设置用于使用配置文件在属性源中分隔配置文件名称的分隔符的值
        #acl-token: e2c06d18-0486-b43a-a1b0-14e8aefa2788
  mvc:
    view:
      prefix: /WEB-INF
      suffix: .html



